package com.xhb.sockserv.util;

public class XmlMsgTemplate {
	public static String SQUENCEXML = ""
			+ "<?xml version=\"1.0\" encoding=\"utf-8\"?>"
			+ "<root>"
			+ "<common>"
			+ "<building_id>楼栋编号</building_id>"
			+ "<gateway_id>采集器编号</gateway_id>"
			+ "<type>sequence</type>"
			+ "</common>"
			+ "<id_validate operation=\"sequence\">"
			+ "<sequence>16位序列随机序列</sequence>"
			+ "</id_validate>"
			+ "</root>";
	public static String MD5VALIDRESPONSEXML = ""
			+ "<?xml version=\"1.0\" encoding=\"utf-8\"?>"
			+ "<root>"
			+ "<common>"
			+ "<building_id>楼栋编号</building_id>"
			+ "<gateway_id>采集器编号</gateway_id>"
			+ "<type>result</type>"
			+ "</common>"
			+ "<id_validate operation=\"result\">"
			+ "<result>验证结果</result>"
			+ "</id_validate>"
			+ "</root>";
	public static String NOTIFYXML = ""
			+ "<?xml version=\"1.0\" encoding=\"utf-8\"?>"
			+ "<root>"
			+ "<common>"
			+ "<building_id>楼栋编号</building_id>"
			+ "<gateway_id>采集器编号</gateway_id>"
			+ "<type>time</type>"
			+ "</common>"
			+ "<heart_beat operation=\"time\">"
			+ "<time>服务器时间</time>"
			+ "</heart_beat>"
			+ "</root>";
	public static String HANDLERESULTOFREPORTDATAXML = ""
			+ "<?xml version=\"1.0\" encoding=\"utf-8\"?>"
			+ "<root>"
			+ "<common>"
			+ "<building_id>楼栋编号</building_id>"
			+ "<gateway_id>采集器编号</gateway_id>"
			+ "<type>report_ack</type>"
			+ "</common>"
			+ "<report_config operation=\"report_ack\">"
			+ "<report_ack>返回值</report_ack>"
			+ "</report_config>"
			+ "</root>";
	public static String READCONFIGAGESXML = ""
			+ "<?xml version=\"1.0\" encoding=\"utf-8\"?>"
			+ "<root>"
			+ "<common>"
			+ "<type>read_age</type>"
			+ "</common>"
			+ "</root>";
	public static String READBUILDINFOXML = ""
			+ "<?xml version=\"1.0\" encoding=\"utf-8\"?>"
			+ "<root>"
			+ "<common>"
			+ "<type>read_build_conf</type>"
			+ "</common>"
			+ "</root>";
	public static String READCOLLECTORINFOXML = ""
			+ "<?xml version=\"1.0\" encoding=\"utf-8\"?>"
			+ "<root>"
			+ "<common>"
			+ "<type>read_col_conf</type>"
			+ "</common>"
			+ "</root>";
	public static String READMETERINFOXML = ""
			+ "<?xml version=\"1.0\" encoding=\"utf-8\"?>"
			+ "<root>"
			+ "<common>"
			+ "<type>read_col_conf</type>"
			+ "</common>"
			+ "</root>";
}
